name: Deploy to Surge 

on:
  push:
    branches: [master]
  repository_dispatch:

jobs:
  DeployApp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies
        uses: jaid/action-npm-install@v1.2.1

      - name: Build Gatsby App
        run: npm run build

      - name: Install Surge
        run: npm i -g surge

      - name: Deploy to Surge
        run: surge ./public https://gatsby-contentful-blog.surge.sh --token ${{ secrets.SURGE_TOKEN }}
